strictness: high
ignore-paths:
  - venv
autodetect: false
max-line-length: 120

mypy:
  run: true
  options:
    ignore-missing-imports: true

pylint:
  disable:
    - too-many-instance-attributes
    - too-many-locals
    - too-many-statements
