set_setpoint_temperature:
  name: Set setpoint temperature
  fields:
    device: &field-device
      name: Komfovent Device
      required: true
      selector:
        device:
          integration: komfovent_c5
          multiple: true
    mode: &field-mode
      name: Mode
      required: false
      default: SPECIAL
      example: COMFORT1
      selector:
        select:
          options:
            - COMFORT1
            - COMFORT2
            - ECONOMY1
            - ECONOMY2
            - SPECIAL
    temperature:
      name: Temperature
      required: true
      example: 20.0
      selector:
        number:
          step: 0.1
          unit_of_measurement: °C
          min: 0.0
          max: 40.0
set_supply_flow:
  name: Set supply flow
  fields:
    device: *field-device
    mode: *field-mode
    value:
      name: Value
      required: true
      selector:
        number:
          step: 1
          mode: box
set_extract_flow:
  name: Set extract flow
  fields:
    device: *field-device
    mode: *field-mode
    value:
      name: Value
      required: true
      selector:
        number:
          step: 1
          mode: box
set_special_mode_config:
  name: Set special mode config
  fields:
    device: *field-device
    dehumidifying:
      name: Dehumidifying
      required: false
      selector:
        boolean:
    humidifying:
      name: Humidifying
      required: false
      selector:
        boolean:
    recirculation:
      name: Recirculation
      required: false
      selector:
        boolean:
    cooling:
      name: Cooling
      required: false
      selector:
        boolean:
    heating:
      name: Heating
      required: false
      selector:
        boolean:
reset_active_alarms:
  name: Reset active alarms
